name: Build for MacOS, Linux, and Windows

on: [push, pull_request]

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [arm64, x86_64]  # Mac architectures: ARM and Intel

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up dependencies on MacOS
      run: |
        echo "Setting up dependencies on MacOS ${{ matrix.arch }}"
        brew install cmake

    - name: Build the project on MacOS
      run: |
        echo "Building project on MacOS ${{ matrix.arch }}"
        cd libbulletc
        mkdir build
        cd build
        cmake -DBUILD_PLATFORM=mac -DCMAKE_BUILD_TYPE=Release ..
        cmake --build .

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-macos-${{ matrix.arch }}
        path: build/